---
- hosts: leafs_DC1, leafs_DC2
  gather_facts: false
  tasks:
    - name: Delete VLANs via looping
      eos_vlans:
        config:
          - vlan_id: "{{ item }}"
            state: active
        state: deleted
      loop:
        - 4000
        - 4001
        - 4002
